name: Windows RDP + Tailscale Login URL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          $pass = "Ad112211"
          net user runneradmin $pass

          Write-Host "=================================="
          Write-Host "RDP USER: runneradmin"
          Write-Host "RDP PASS: Ad112211"
          Write-Host "=================================="

      - name: Download Tailscale MSI
        shell: powershell
        run: |
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-1.96.3-amd64.msi"
          $file = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest $url -OutFile $file
          Start-Process msiexec.exe -ArgumentList "/i `"$file`" /qn /norestart" -Wait

      - name: Start Tailscale Service
        shell: powershell
        run: |
          Start-Service Tailscale
          Set-Service Tailscale -StartupType Automatic

      - name: Show Tailscale Login URL
        shell: powershell
        run: |
          $tailscale = "C:\Program Files\Tailscale\tailscale.exe"

          if (!(Test-Path $tailscale)) {
            $tailscale = "C:\Program Files (x86)\Tailscale\tailscale.exe"
          }

          & $tailscale up --accept-routes --accept-dns=false

      - name: Keep Runner Alive
        shell: powershell
        run: |
          while ($true) {
            Start-Sleep -Seconds 60
          }
